---
- name: Configuring tomcat9
  hosts: all
  tasks: 
    - name: Install tomcat9
      apt: 
        name: tomcat9
        state: present

    - name: Install tomcat9-admin
      apt:
        name: tomcat9
        state: present

    - name: Copy tomcat-users.xml file
      copy: 
        src: tomcat-users.xml
        dest: /etc/tomcat9/

    - name: Change port from 8080 to 9090
      replace: 
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: Restart tomcat9
      service:
        name: tomcat9
        state: restarted 
    - name: Pause for 1 min
      pause: 
        minutes: 1
    - name: Check tomcat9 response on server1
      uri:
        url: http://172.31.7.82
        status_code: 200
    - name: Check tomcat9 response on server2
      uri:
        url: http://172.31.14.56 
        status_code: 200
         
...
