--- 
- name: configure apache2 or httpd based on OS
  hosts: all
  tasks: 
     - name: Install apache2 using apt
       apt: 
         name: apache2
         state: present
         update_cache: yes
       when: ansible_distribution == "ubuntu"    
     - name: Install httpd using yum
       yum: 
         name: httpd
         state: present
         update_cache: yes
       when: ansible_distribution == "RedHat"
     - name: Edit the index.html file
       copy:
         content: "Welcome to DevOps"
         dest: /var/www/html/index.html  
     - name: Restart apache2 on ubuntu
       service:
         name: apache2
         state: restarted
       when: ansible_distribution == "ubuntu"    
     - name: Restart httpd on ubuntu
       service:
         name: httpd
         state: restarted
       when: ansible_distribution == "RedHat"
     - name: check apache2 or httpd response
       uri:
         url: "{{item}}"
         status_code: 200
       with_items:
         - http://172.31.15.152
         - http://172.31.60.232
         - http://172.31.7.82
         - http://172.31.14.56    

